allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  unrs-resolver: false
minimumReleaseAgeExclude:
  - '@vesperjs/shared@0.9.14'
overrides:
  '@typescript-eslint/typescript-estree': ^8.63.0
  eslint: ^10.7.0
  typescript-eslint: ^8.63.0
  vite: ^8.0.16
