allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  unrs-resolver: false
overrides:
  '@typescript-eslint/typescript-estree': ^8.59.3
  eslint: ^10.3.0
  typescript-eslint: ^8.59.3
  vite: ^8.0.12
