allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  unrs-resolver: false
overrides:
  '@typescript-eslint/typescript-estree': ^8.59.4
  eslint: ^10.4.0
  typescript-eslint: ^8.59.4
  vite: ^8.0.14
